import { Octokit } from '@octokit/rest';
import type { ExtractedTicket, ClarifyResult, ClairifaiConfig } from '../types.js';
import { createError } from '../errors.js';

const CONFIDENCE_LABELS: Record<string, string> = {
	HIGH: 'confidence:high',
	MEDIUM: 'confidence:medium',
	LOW: 'confidence:low',
};

const TYPE_LABELS: Record<string, string> = {
	FEATURE: 'feature',
	BUG: 'bug',
	SPIKE: 'spike',
	TECH_DEBT: 'tech-debt',
};

function formatTicketBody(ticket: ExtractedTicket, review?: ClarifyResult['reviewed_tickets'][number]): string {
	const sections: string[] = [];

	// User story / Problem statement / Research question
	if (ticket.user_story) {
		sections.push(`## User Story\n\n${ticket.user_story}`);
	}
	if (ticket.problem_statement) {
		sections.push(`## Problem Statement\n\n${ticket.problem_statement}`);
	}
	if (ticket.research_question) {
		sections.push(`## Research Question\n\n${ticket.research_question}`);
	}
	if (ticket.current_state) {
		sections.push(`## Current State\n\n${ticket.current_state}`);
	}

	// Context
	sections.push(`## Context\n\n${ticket.context}`);

	// Acceptance Criteria
	if (ticket.acceptance_criteria.length > 0) {
		const acLines = ticket.acceptance_criteria.map(ac =>
			`- [ ] **Given** ${ac.given} **When** ${ac.when} **Then** ${ac.then}${ac.inferred ? ' *(inferred)*' : ''}`
		);
		sections.push(`## Acceptance Criteria\n\n${acLines.join('\n')}`);
	}

	// Technical Notes
	if (ticket.technical_notes) {
		sections.push(`## Technical Notes\n\n${ticket.technical_notes}`);
	}

	// Out of Scope
	if (ticket.out_of_scope.length > 0) {
		sections.push(`## Out of Scope\n\n${ticket.out_of_scope.map(s => `- ${s}`).join('\n')}`);
	}

	// Decisions
	if (ticket.decisions.length > 0) {
		const decisionLines = ticket.decisions.map(d =>
			`| ${d.decision} | @${d.made_by} | ${d.timestamp} |`
		);
		sections.push(`## Decision Log\n\n| Decision | Source | Timestamp |\n|----------|--------|-----------|`
			+ '\n' + decisionLines.join('\n'));
	}

	// Open Questions
	if (ticket.open_questions.length > 0) {
		const qLines = ticket.open_questions.map(q =>
			`- **[${q.priority}]** ${q.question}`
		);
		sections.push(`## Open Questions\n\n${qLines.join('\n')}`);
	}

	// Review notes
	if (review) {
		sections.push(`## Review Notes\n\n${review.review_notes}`);
	}

	sections.push(`\n---\n*Generated by CLAIRIFAI*`);

	return sections.join('\n\n');
}

export async function createGitHubIssues(
	tickets: ExtractedTicket[],
	reviewed: ClarifyResult,
	config: ClairifaiConfig,
): Promise<{ created: number; errors: string[] }> {
	const token = process.env['GITHUB_TOKEN'];
	if (!token) {
		throw createError('GITHUB_TOKEN_MISSING');
	}

	if (!config.repo) {
		throw createError('GITHUB_PUSH_FAILED', 'No repo configured in .clairifai.json');
	}

	const [owner, repo] = config.repo.split('/');
	const octokit = new Octokit({ auth: token });

	let created = 0;
	const errors: string[] = [];

	for (const ticket of tickets) {
		const review = reviewed.reviewed_tickets.find(r => r.ticket_id === ticket.id);
		const labels = [
			TYPE_LABELS[ticket.type] ?? ticket.type.toLowerCase(),
			CONFIDENCE_LABELS[ticket.confidence] ?? '',
			'clairifai',
		].filter(Boolean);

		try {
			await octokit.issues.create({
				owner,
				repo,
				title: `[${ticket.type}] ${ticket.title}`,
				body: formatTicketBody(ticket, review),
				labels,
			});
			created++;
		} catch (err) {
			errors.push(`Failed to create issue for "${ticket.title}": ${err instanceof Error ? err.message : String(err)}`);
		}
	}

	return { created, errors };
}
